name: Lint Helm Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v4.2.0
        with:
          version: 'latest'

      - name: Run chart-testing (lint)
        run: helm lint ./chart/nfs-subdir-external-provisioner
